CHANGELOG.md, netlify.toml, scripts/cibuild, scripts/lint, scripts/test, src/app/package.json
Create configuration for building and deploying the application via Netlify. Since Netlify doesn't have docker-compose, adapts `cibuild` to use yarn commands directly.
Connects #2 
- Locally, confirm you can still run `./scripts/lint` and `./scripts/test` on your VM.
- Confirm that the build passes and the site is preview-deployed for this application in the Checks section below
https://deploy-preview-5--gender-survey-dashboard.netlify.app/
=> Add build and deploy configuration for Netlify

deployment/ansible/roles/fb-gender-survey.docker/tasks/main.yml
This accounts for alternate Ansible version scenarios where
`ansible_user` is not available. docker_users is always there because
we define it inside of group_vars/all.
* Run ./scripts/setup` and the environment should provision successfully
=> Ensure docker_users is used instead of ansible_user

CHANGELOG.md, src/app/src/App.js, src/app/src/components/Breadcrumbs.js, src/app/src/components/QuestionSelector.jsx, src/app/src/components/Visualizations.jsx, src/app/src/utils/constants.js
Adds breadcrumbs to the Question and Visualization components.
There's some extra logic to allow us to easily hook them in to
the Saved Charts page when we've built it.
While it might have been possible to create dynamically generated
breadcrumbs, making it a bit more declaratory simplified the code
significantly. Similarly, it would probably be possible to locate this
at the top level instead of in the specific components where it appears,
but because we are only going to be using it on three screens, the
extra logic seemed like an over-complication.
To keep the breadcrumbs and the route paths coordinated, I moved the
route paths to a ROUTES object in the constants file.
Connects #10 
* Navigate to the homepage. You shouldn't see breadcrumbs.
* Select a country/region and click next. You …
=> Add Breadcrumbs

src/app/src/App.js, src/app/src/components/AboutModal.jsx, src/app/src/components/FaqModal.jsx, src/app/src/components/Header.jsx
The app header contains two level of hierarchy for titles, as well as a
link bar for navigation or modal dialog display. Add stubs for the two
modals, as well as some basic content manipulation depending on which
page sequence is currently active.
Connects #18 
First page, large format:
Subsequent pages, condensed format
The visual design feedback doc has a number of header content related changes under discussion, so I opted for a bare-bones implementation for now. There are also two follow up tasks for adding content to the modals (#31) and potentially some dynamic values in the sub-header text (#30). Even though the designs don't indicate it, I believe the "Saved Charts" link will always be present, whether or not there are currently any saved (this is also currently being discussed in …
=> Add app header

CHANGELOG.md, src/app/src/components/GroupedBarChart.js
Adds the bar chart for grouped responses.
Connects #22 
Many countries
Few countries
The bars auto-resize to fit the height of the container. We could probably calculate a larger height for the container based on the number of countries/regions included if we'd rather the container grow instead of the items shrink. 
* Select a number of countries or regions
* Select a question with a bolded answer (ie 'Head of Household')
* The chart should render the data correctly
* The chart should show all selected countries
=> Add Grouped Bar Chart

src/app/src/components/GeographySelector.jsx, src/app/src/components/QuestionSelector.jsx
When returning to the geography selector page, check the boxes that are represented in current state. Additionally, use local state to track the previous "geo selection mode" selected values, so they can be restored when that mode is re-enabled. Prevent both regions and countries from being selected at once.
When navigating back to the question page (from the viz page), select any checkboxes that
match the currently selected state. Additionally, expand any category accordions which have selected checkboxes.
Lastly, now that the user can navigate backwards, it was possible to go from Viz (with questions already selected) back to Geography, and then next to Questions again. This would leave the previously selected questions checked, causing the user to have to manually adjust them. It's not …
=> Persist checkbox state

CHANGELOG.md, src/app/src/components/WaffleChart.js
Adds a Waffle chart component for displaying 'out of ten' questions. Unlike the bar chart, axis labels aren't available for the Waffle Chart, so I was unable to include the country name in the chart itself. However, I was able to tweak the legend component enough (because the Waffle chart does provide customized legend labels) and use that to create a gender/count label. Note that each gender Waffle chart is a separate canvas element. 
Connects #23 
* Select several countries or regions. 
* Select a few 'out-of-ten' questions.
* Navigate to the visualizations page and confirm that the chart data and label display the correct information.
=> Add waffle chart

CHANGELOG.md, src/app/package.json, src/app/src/components/Visualizations.jsx, src/app/src/index.js, src/app/src/redux/reducers.js, src/app/src/redux/store.js, src/app/src/redux/visualizations.actions.js, src/app/src/redux/visualizations.reducer.js, src/app/yarn.lock
Users are able to click 'save' while on the visualizations page,
and store their currently selected geographies/questions/etc. into
local storage.
Data is stored in an array of objects, with each object containing a
title and the information needed to recreate the visualization. 
The stored visualization does NOT include the survey data, which means 
that we don't capture stale state data if the dataset changes. 
However, when completing the follow-up UI tasks we will need to 
gracefully handle cases where a persisted question or geography 
is no longer available.
Connects #19 
* Select geographies and questions, then click 'save' on the visualizations page. 
* View Redux state and local storage and confirm that the visualization data has been added. 
* Add additional visualizations and …
=> Save visualizations

.github/ISSUE_TEMPLATE/release.md, README.md
The contents of this PR add documentation and instruction on how to create and manage production releases. It is expected that future planned release will create a new `Release` issue and follow the instructions.
Separately, the following were also done to enable production releases:
- Added a `master` branch
- Set `master` as the production branch in the Netlify settings for this site
- Moved `develop` to and "additional" deployment site in the Netlify settings
- Followed the instructions in the release template to cut an initial release at 0.1.0
Going forward, merging into `develop` should deploy to https://develop--gender-survey-dashboard.netlify.app/ and cutting a release (which merges `develop` -> `master`) should deploy to https://gender-survey-dashboard.netlify.app/. PR deploy …
=> Allow production releases

CHANGELOG.md, src/app/src/App.js, src/app/src/components/EditableTitle.js, src/app/src/components/Header.jsx, src/app/src/components/SavedVisualizations.js, src/app/src/components/Visualizations.jsx, src/app/src/redux/app.actions.js, src/app/src/redux/app.reducer.js, src/app/src/redux/visualizations.actions.js, src/app/src/redux/visualizations.reducer.js, src/app/src/utils/constants.js, src/app/src/utils/index.js
Allows users to manage saved visualizations. Users can load the visualizations' list from local storage, edit their titles, and navigate to a specific visualization.
Connects #20 
* Select 'saved charts' in the header. 
* You should see a list of saved charts.
* Hover over the title of one chart, then click the edit button.
* You should be able to edit the title in an inline input, then click submit. On refreshing the page, the title should remain edited. 
* You should be able to edit the title, then click cancel. The title should revert to its previous state. 
* You should be able to click within the list item, outside of the buttons or input, to be taken to the saved visualization.
* The questions and geographies for the saved visualization should match the stored values. 
* Add an …
=> View saved visualizations

CHANGELOG.md, src/app/src/App.js, src/app/src/components/NotFound.js
Adds a page for attempts to access routes which don't exist.
Connects #46 
* Open the Netlify preview. 
* Enter a route that doesn't exist, such as '/test'
* The 404 page should show
* Follow the link to home on the 404 page
* Traverse the real routes and confirm that the app works as before
=> Add a 404 Not Found Page

CHANGELOG.md, src/app/src/components/GeographySelector.jsx, src/app/src/components/QuestionSelector.jsx, src/app/src/components/SearchInput.js, src/app/src/utils/index.js
Allows the list of geographies or questions to be narrowed down to labels which contain the user input.
For the list of geographies, if a user selects an item and then changes the search term, the selected item is shown regardless of if it matches the current query. Text is shown to indicate no results found.
For the list of questions, questions are shown if the question or the answer/cat matches. If no matches are found for a category, that category is replaced by text stating that no results were found. 
Connects #24 
Filtered results + previously selected
No results
Filtered Questions
Questions with some empty sections
* Open the Netlify preview. 
* Enter a search term and confirm the list of regions is filtered. Select a region. 
* Enter a new region. The list should be filtered but …
=> Filter Questions and Geographies

src/app/src/App.css, src/app/src/components/Chart.js, src/app/src/components/DownloadMenu.jsx, src/app/src/components/GroupedBarChart.js, src/app/src/components/StackedBarChart.js, src/app/src/components/WaffleChart.js, src/app/src/hooks/useRefs.js, src/app/src/utils/canvas.js
All of the Nivo chart types implemented in the app render to Canvas. As
a result, we can generate a dataUrl for each canvas element and offer it
as a direct image download. A new button is available on every individual
chart (or chart group in the case of Waffle) which gives a menu to download
the image as PNG.  
A few workarounds are needed to accomplish
this:
- A ref to a particular container element is required in order to
generically search for a child canvas element
- Waffle charts are really a sequence of three separate charts that
should be treated as one
- Nivo charts have a transparent background, and a solid color needs to
be applied before writing
As a result of these extra requirements, there is some manual
manipulation of the canvas element to represent enough chart context …
=> Download chart as PNG image option

CHANGELOG.md, src/app/package.json, src/app/src/components/GroupedBarChart.js, src/app/src/components/Visualizations.jsx, src/app/src/utils/index.js
- Nivo tooltips move with cursor locally and when deployed
- Round values to hundredths
- Hide empty chart categories
- Maintain consistent order of regions for charts
Connects #38 
Rounded values
Grouped chart with correct ordering
Hidden empty sections
* In the deploy preview, select multiple regions and at least one question of each chart type. Don't select questions from every category.
* Move your cursor around on the charts and confirm the tooltip follows your cursor.
* Confirm the values in the tooltips have two decimal places.
* Confirm that the order of the regions is the same for each chart type. 
* Confirm that the categories with no selected questions are hidden.
=> Visualizations Page Cleanup

CHANGELOG.md, src/app/src/components/GroupedBarChart.js, src/app/src/components/Visualizations.jsx
More clearly expresses the data in percentage charts by setting their
limit to 100, and formatting ticks and tooltips as percentages.
Adds locale formatting to non-percentage grouped bar charts.
Also switches the format of keys for charts to prevent duplicate key
warnings.
Connects #56 
We chose to leave the current types as-is, even though `hours` and `null` type charts are handled identically at the moment, in order to allow for differentiation in the future if desired. 
* In the deploy preview, select several percentage-type questions, hours-type questions, and null-type questions. 
* Confirm that the percentage charts show percentages in the axis and the tooltip, and that they are set to limits of 0%-100%.
* Confirm that the hours- and null-type questions are working as before with …
=> Handle Percentage Charts

CHANGELOG.md, src/app/src/components/QuestionSelector.jsx
Allows users to select/deselect all questions in a category by toggling
the category checkbox.
Connects #60 
* In the deploy preview, select a region or country and continue to questions. 
* Open a category and select a question. The category should move to an indeterminate checkbox. 
* Select the category checkbox. All questions in the category should be selected. 
* Deselect one question in the category. The category should move to an indeterminate state. 
* Reselect the question and the checkbox should move to a selected state. 
* Deselect the checkbox. All questions in the category should be deselected. 
* Manually select all questions in the category. The category should be marked selected. 
* Manually deselect all questions in the category. The category should be marked unselected. …
=> Allow Question Category Select-All/None

CHANGELOG.md, src/app/src/components/DownloadMenu.jsx, src/app/src/components/GroupedBarChart.js, src/app/src/components/StackedBarChart.js, src/app/src/components/Visualizations.jsx, src/app/src/components/WaffleChart.js, src/app/src/utils/csv.js
Users can download selections of the data for each chart or for the
visualizations page as a whole. The chart contains the columns
Geography, Question Code, Question Text, Response Category,
Response Variable, Gender, and Value, with a varying number of rows
per chart type. The filename contains the question codes for the
requested data, ie `A.1_B.1_gender_survey.csv`.
Connects #59 
Stacked
Waffle
Grouped
All Selected Questions
* In the deploy preview, select multiple regions and multiple questions (at least one question of each type).
* For each chart, download the CSV. Confirm that the data is correct and is formatted correctly, and the filename makes sense. 
* Click the 'download' button at the top of the page. Confirm that the data and filename are correct. 
* Test in multiple …
=> Download CSVs

CHANGELOG.md, src/app/src/components/GeographySelector.jsx, src/app/src/components/Header.jsx, src/app/src/components/QuestionSelector.jsx, src/app/src/components/SavedVisualizations.js, src/app/src/components/SearchInput.js, src/app/src/utils/constants.js
Updates large and small version of header to more closely match
current designs.
Updates text throughout website, specifically:
- Change "Choose one or more areas to analyze" to "Start by selecting
Regions or Countries".
- Update subtext under main title, per Dashboard text doc.
- Add explanatory text above the question categories
- Add text above the saved charts tiles explaining that deleting cookies
can impact saved charts
- Call charts "charts" (not visualizations) on saved charts page
Connects #62 
* In Netflify preview, confirm that the header text and style on the geographies page matches the mockups and [feedback document](https://docs.google.com/spreadsheets/d/1jeDH5uchMijCl4gXCEs-LHNEmVcAx-mYhoIb1S8XVC0/edit#gid=0). 
* On the questions page, confirm that the header style and the …
=> Text Copy and Header Changes

CHANGELOG.md, src/app/src/components/AboutModal.jsx, src/app/src/components/FaqModal.jsx, src/app/src/components/StyledAccordion.js
Adds content for the FAQ and About modals. 
Connects #31 
Ordinarily with a component with this much repetition in structure, if pulling from an API, one would use a mapped list to minimize code. However, in this particular case, the presence of links in the text content adds some complication to this logistically. In addition, since the text is stored locally, we would wouldn't actually be saving many lines of code. In the end, it seemed simplest and clearest to hard-code the sections/content, but use styled components for the repetitious portions of the structure. This allows us to still edit styling of the sections all at once if needed.
* In the Netlify preview, click the 'FAQ' button. It should open the correct modal. Clicking the accordions should toggle them.
* Confirm the content …
=> Add modal content

CHANGELOG.md, src/app/src/App.js, src/app/src/components/SurveyNotification.js, src/app/src/components/Visualizations.jsx, src/app/src/redux/reducers.js, src/app/src/redux/store.js, src/app/src/redux/survey.actions.js, src/app/src/redux/survey.reducer.js
The survey is hidden until 30 seconds after the user has first visited
the visualizations page, at which point the survey notification will
be rendered at the top of the view. The survey notification is set to a
fixed position so that it will be visible on rendering, regardless of
if the user has scrolled down the page, and will appear on any page
which the user is on.
After the initial rendering, the survey will continue to be displayed
until the user has clicked the survey link or has closed it, after which
the survey will not appear again.
The survey status is stored in a persisted reducer to be consistent
with how we have managed other local storage data.
Connects #69 
* Navigate to the Visualizations page in the Nelify preview. The survey notification shouldn't show. 
* Wait for 30 …
=> Add Survey Notification

CHANGELOG.md, src/app/src/components/GroupedBarChart.js
Adjusts the height of the grouped bar chart based on the number of
items in order to prevent items from shrinking to an unreadable level
when large numbers of items are present.
Connects #74 
One Item
Many Items
* In the Netlify preview, select one country and a grouped chart question. The chart should render to a reasonable height. 
* Select many countries and a grouped chart question. The chart should render to a reasonable height.
=> Adjust Grouped Bar Height

CHANGELOG.md, src/app/src/components/GroupedBarChart.js, src/app/src/components/StackedBarChart.js, src/app/src/components/WaffleChart.js
Final confirmed colors for charts match the current mockups for Grouped
and Waffle charts, specifically:
- Women: rgb(54, 17, 52) (Dark Red)
- Men: rgb(220, 56, 70) (Red)
- Total: rgb(243, 164, 142) (Pink)
Final confirmed colors for Stacked charts were requested to use the
same colors as for the Grouped and Waffle charts (differing from current
designs), specifically:
- Disagree: rgb(54, 17, 52) (Dark Red)
- Neutral: rgb(243, 164, 142) (Pink)
- Agree: rgb(220, 56, 70) (Red)
Connects #65 
The colors for the bar charts are reversed from the designs because of the way horizontal charts are flipped by Nivo. With the current code for Nivo, we can't reverse these without also reversing the order of the items in the legend/key for each chart. For stacked charts, it might be reasonable to do this …
=> Update Chart Colors

CHANGELOG.md, src/app/src/components/QuestionSelector.jsx
When the user enters a search term on the questions page, categories
are automatically opened if they contain matching questions, and closed
if they have no matching questions. Note that this means that if the
user has manually opened or closed a category, then enters or changes a
search, the expansion of the accordion will be changed, as there isn't
a reasonable way to track which categories have been manually toggled
by the user.
Connects #73 
* In the Netlify preview, select a geography and move to the questions page. Enter a search - categories with matching items should open. 
* Type a search that will not match any questions - the categories should close. 
* Select some questions, go to the charts page, and return. Selected categories should open by default on page load as before.
=> Open Categories in Response to Search

CHANGELOG.md, src/app/src/components/QuestionSelector.jsx
StackedChart items ('agree or disagree') weren't being matched by the
question search, because for these items multiple survey responses are
nested under one question code. We therefore need to compare the
query to multiple responses for these questions, using the question code
instead of the response code.
Connects #78 
* On [staging](https://develop--gender-survey-dashboard.netlify.app/visualization), select some countries and click 'next'.
* Enter 'expense' into the search bar - you will see three questions found. 
* In the Netlify preview for this PR, select some countries and click 'next'. (You can find the Netlify preview link near the merge button below - where it says, 'deploy/netlify' click the 'details' link). 
* Enter 'expense' into the search bar - you will see four questions …
=> Fix Question Filtering

CHANGELOG.md, src/app/src/components/DownloadMenu.jsx, src/app/src/components/SearchInput.js, src/app/src/utils/canvas.js
Adds the survey questions, answers, and codes as titles to the chart
downloads. For waffle charts, include the geography as part of the title.
Recent updates to the query input caused it to refresh the page on submission. 
Fixes that by preventing submission.
Connects #27 and #96
Stacked Chart:
Waffle Chart:
Grouped Chart:
* In the Netlify preview, select some number of locations
* On the questions page, select several questions, at least one of each type ('agree or disagree', 'out of ten', and ones with 'Answered')
* On the charts page, hover over a chart to see the download button. Click it, and in the menu select 'png'
* A chart should download. Open it and confirm that it has the question code and question, the answer where applicable, and the location if it is a waffle chart, as a …
=> Add Titles to Chart Downloads

CHANGELOG.md, src/app/src/components/AboutModal.jsx
Adds a link to the source code and license information to the About
modal.
* In the Netlify preview, open the 'about' modal. Confirm that there is a new accordion item called 'Source code' that contains a link to the source code.
=> Add License Information to About

netlify.toml
Netlify isn't able to recognize the submodule changes to the data.
It's therefore cancelling the build on master and preventing a
deployment. This updates the Netlify build settings to deploy the app
when the `master` branch is updated, even if there are no visible
changes.
=> Force Netlify Build

CHANGELOG.md, Vagrantfile, deployment/ansible/group_vars/all
The setup script is failing due to a pip error following the url for get-pip changing. We have seen this on several other projects, and it has been repaired by specifying the correct URL in the Vagrant file.
Connects #106 
* Run `./scripts/setup` and confirm that the build succeeds. 
* In Vagrant, run `./scripts/update` and `./scripts/server`. The app should load and run correctly at http://localhost:3333.
=> Update get-pip url

CHANGELOG.md, netlify.toml
Updates Equality at Home to allow cross-origin requests to support
embedding the Equality at Home site within the Data for Good page.
Connects #108 
* Confirm the app can be embedded by viewing it this deploy preview in an iframe in [a test page](https://taiwilkin.github.io/test-iframe/).
=> Enable Cross-Origin Requests

.gitignore, CHANGELOG.md, README.md, src/dataproc/generate_data.py
Until the 2021 data is live on HDX, we will need to use local data
for development. Updates the URIs for the data to point to local copies
of the data files.
Connects #107 
This partially undoes the work done in [issue 53](https://github.com/azavea/fb-gender-survey-dashboard/pull/53). 
This update should have resulted in no changes to the data as of yet, because we are still using the 2020 data set, albeit locally. 
* Download the two Excel sheets (sog_agg_region and sog_agg_country) from the Gender Equality Google Drive. 
* Follow the directions in the Readme under `Data` and `Updating application with new data`. 
* Run `./scripts/server`.
* Confirm that the app functions as before.
=> Use local data for development

CHANGELOG.md, src/app/src/components/QuestionSelector.jsx, src/app/src/components/Visualizations.jsx, src/app/src/utils/index.js
While some questions were asked in both years, some questions were only
asked in 2020 or 2021. After users select a year, they should only see
questions which are applicable in the currently selected year.
Also adds the selected year(s) to the displayed information at the top of each page.
Connects #113 
* This is a fully frontend issue, so it can be tested in the Netlify preview. 
* Select several countries or regions and the year 2020.
*  Navigate to the questions page. Note the number of questions that are available in each category. 
* Select questions using the both the individual questions checkboxes and the category checkboxes. 
* View the charts page and confirm the selected questions are displayed. 
* Return to the years page and select 2021. 
* Navigate to the questions page. …
=> Hide unavailable questions

CHANGELOG.md, src/app/src/components/DownloadMenu.jsx, src/app/src/components/GroupedBarChart.js, src/app/src/components/StackedBarChart.js, src/app/src/components/WaffleChart.js, src/app/src/utils/csv.js, src/app/src/utils/index.js
Now that multiple years are available, users should be able to see in
their downloads which year is being displayed in PNGs and CSVs.
Adds the year to each response row in the CSV downloads.
Adds the year to the question / title of the waffle chart, which will only ever
display one year. Adds the year beside each bar in the bar charts (which
will show multiple years in comparison view).
Connects #117 
For the bar charts, which will be reused for comparative view, I have followed the mockup in [the SOW](https://drive.google.com/drive/u/0/folders/1RM4jKy_3euv6cVq0BXcUe-KHxnWs4d1S) in adding the year. 
* Select a geography and year in the Netlify preview, then select at least three questions: an 'out of 10' question (waffle chart), an 'agree / disagree' question (stacked bar chart), and a …
=> Show year in charts and downloads

CHANGELOG.md, src/app/src/components/DownloadMenu.jsx
After upgrading ChakraUI, the menu for the download menu was rendered
but hidden prior to being opened. This caused a gap the width of the
menu to appear to the right of the charts, resulting in charts scrolling
horizontally even on full-screen (charts are expected to scroll on
mobile only).
Rendering the menu list in a portal prevents the menu from effecting
the page layout, fixing the horizontal scroll.
Connects #127 
Horizontal Scroll:
No Scroll:
* On [staging](https://develop--gender-survey-dashboard.netlify.app), select some geographies and a question of each type (agree/disagree, out of ten, other), then attempt to scroll right on a chart. You will see the chart scroll and a gap appear at the right. Open the download menu and the gap will vanish. 
* In the Netlify preview for this …
=> Fix horizontal chart scrolling

CHANGELOG.md, src/app/src/components/QuestionSelector.jsx, src/app/src/components/StackedBarChart.js, src/app/src/components/Visualizations.jsx, src/app/src/components/WaffleChart.js, src/app/src/components/YearSelector.jsx, src/app/src/utils/index.js
Users can select multiple years on the years selection page, and
questions are formatted appropriately for multiple years.
Questions/options are hidden on the question selection page only if
they are unavailable for all selected years for all selected
geographies.
Displays comparative view for StackedBarChart and GroupedBarChart by adding a row for each answer type
for each year.
Connects #133, #135, #136 
Comparative view design for WaffleCharts hasn't been finalized, so for the moment, each year / country will load as a separate set of waffle charts. Comparative view for WaffleChart question will be built in #137.
* In the Netlify preview, select a country with only 2020 data. Only 2020 should be available on the years page.
* Select a country with only 2021 data. Only 2021 should be …
=> Allow users to select multiple years

CHANGELOG.md, src/app/public/index.html, src/app/src/App.js, src/app/src/utils/index.js
Updates the meta tags to use new text for 2021 (swapping out "Visualize aggregate data from over the 2020 Survey on Gender Equality at Home, which reached over 460,000 Facebook users in 208 locations around the world" with "Explore the country and region-level data from the 2020 and 2021 waves of the Survey on Gender Equality at Home.") per client request. 
Adds protections to handle a null or invalid geoMode. The geography mode (region or country) must be selected for the app to successfully access the data and work as expected. This value is set to countries by default, but in the case of an invalid value somehow entering the system, the app will reset the value to countries, and prevent content from loading until a valid value is found.
Connects #131, #139
A separate commit with an …
=> Update meta tags and handle null geoMode

CHANGELOG.md, src/app/src/components/GroupedBarChart.js, src/app/src/components/StackedBarChart.js
Orders the years listed in the charts from least- to most-recent
and adds a gap in between the years to keep the data distinct.
Connects #141 
* In the Netlify preview, select two locations which are available in multiple years and select multiple years. 
* Select a multi-year StackedBarChart question and a GroupedBarChart question (such as "How many other people live with you under the same roof? Please do not count yourself" and "Do you agree or disagree with the statement? "There are times when I feel uncomfortable or even unsafe in my house.""). 
* View the charts and confirm they are styled with a gap in between the years and the years are ordered.
=> Format comparative bar charts

CHANGELOG.md, src/app/src/components/Chart.js, src/app/src/components/GroupedBarChart.js
Some questions contain the phrase 'out of ten of your neighbors...'
These questions are formatted as WaffleCharts when viewed as a
single-year chart. However, because each piece of data must be
rendered as a separate waffle chart, this isn't conducive for
comparative view. When viewed with multiple years selected, these
questions are instead displayed as a GroupedBarChart with the maximum
value set to 10.
Connects #137 
* Select geographies that cover multiple years, select multiple years, and select all of the available 'out of 10' questions. Select several grouped bar chart questions that are not 'out of 10' as well.
* The charts should be bar charts. The maximum value for the 'out of 10' charts should be 10. The other bar charts should work as before. 
* Select the same geographies, a …
=> View 'out of ten' charts in comparative view

CHANGELOG.md, src/app/src/components/DownloadMenu.jsx, src/app/src/utils/csv.js
Updates the comparative chart download to correctly format the comparative "out of ten" chart titles. 
Connects #118 
* Select a combination of geographies for multiple years and geographies for one year, then select multiple years and a question of each type (stacked bar chart, grouped bar chart, and waffle / out-of-ten chart). 
* Download the image for each chart.
* Download the CSV for each chart.
* Download the CSV for the full page.
* Repeat the above steps with only one year selected. 
* The images and CSVs should download correctly and without errors.
=> Allow comparative chart download

src/dataproc/Dockerfile
When pre-built wheels are not available for certain architectures, like the new M1 Apple Silicons, they need to be built locally in the container. The Python Slim container does not come with build tools by default.
This adds the build tools before installing dependencies, then removes them so the image stays slim.
* Run `update`
=> Add build tools in dataproc container
